---
kind: pipeline
type: docker
name: test

steps:
  - name: build-local
    image: node:lts-alpine
    commands:
      - npm ci && npm run build
  - name: test
    image: node:lts-alpine
    commands:
      - npm run test
  - name: deploy to npm
    image: plugins/npm
    when:
      branch: publish
    settings:
      email: mauriceprivat98@gmail.com
      username: mauricenino
      password:
        from_secret: NPM_ACCESS_KEY

---
kind: secret
name: NPM_ACCESS_KEY
data: yAgY1nQbathhkCiwocMeYdMd9w/nkuoNgiBt+WkBvzHjpPBS3lnqYWK+HR1HgEYIZlBG1LB265DPX/sqB7d9ZNc8rxU=
---
kind: signature
hmac: 2e0a5b46756a19183e96d3101dc77d60ec03021cf59aec47e0e46ff65e6351d5
